/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.hmsoft.libcommon;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static int detail_mode_icon_burst=0x7f020000;
        public static int detail_mode_icon_continuous=0x7f020001;
        public static int detail_mode_icon_photo=0x7f020002;
        public static int detail_mode_icon_timelapse=0x7f020003;
        public static int detail_mode_icon_video=0x7f020004;
        public static int icon_power=0x7f020005;
        public static int icon_setting_up=0x7f020006;
    }
    public static final class string {
        public static int action_mode_burst=0x7f030000;
        public static int action_mode_photo=0x7f030001;
        public static int action_mode_timelapse=0x7f030002;
        public static int action_mode_video=0x7f030003;
        public static int preference_category_watch_key=0x7f030004;
        public static int preference_category_wifi_key=0x7f030005;
        public static int preference_screen_main_key=0x7f030006;
        public static int preference_watch_shake_level_key=0x7f030007;
        public static int preference_watch_shake_shutter_mode_key=0x7f030008;
        public static int preference_wifi_name_key=0x7f030009;
        public static int preference_wifi_password_key=0x7f03000a;
        public static int preference_wifi_restore_network_key=0x7f03000b;
        public static int preference_wifi_test_key=0x7f03000c;
    }
}
